version: '3.7'

services: 
    mongo:
        container_name: mongo-container
        image: mongo:4.2.7
        restart: always
        ports: 
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME: mongodb
            MONGO_INITDB_ROOT_PASSWORD: mongodb        
        volumes: 
            - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
